plagues = {
    "lagarta_elasmo": "Lagarta Elasmo",
    "lagarta_helicoverpa_spp": "Lagarta Helicoverpa spp",
    "lagarta_heliothis": "Lagarta Heliothis",
    "lagarta_falsa_medideira": "Lagarta Falsa Medideira",
    "lagarta_da_soja": "Lagarta da Soja",
    "spodoptera_frugiperda": "Spodoptera Frugiperda",
    "spodoptera_eridania": "Spodoptera Eridania",
    "spodoptera_cosmioides": "Spodoptera Cosmioides",
    "spodoptera_albula": "Spodoptera Albula",
    "tamandua_da_soja": "Tamanduá da soja",
    "percevejos": "Percevejos",
    "tripes": "Tripes",
    "acaros": "Ácaros",
    "cigarrinha": "Cigarrinha",
    "mosca_branca": "Mosca Branca",
    "mancha_alvo": "Mancha Alvo",
    "mancha_parda": "Mancha Parda",
    "antracnose": "Antracnose",
    "mofo_branco": "Mofo Branco",
    "mildio": "Míldio",
    "oidio": "Oidio",
    "ferrugem_asiatica": "Ferrugem Asiática",
}

biotechnologies = {
    'desiccation': 'Dessecação pré-plantio',
    'certified_seeds': 'Sementes certificadas',
    'seed_handling': 'Tratamento de sementes',
    'refuge': 'Refúgio Agrícola',
    'weeds': 'Controle de Plantas daninhas',
    'plague_monitoring': 'Monitoramento de pragas',
}

pesticides = {
    'acefato': 'Acefato',
    'atrazina': 'Atrazina',
    'bifentrina': 'Bifentrina',
    'curbix': 'Curbix',
    'diurum': 'Diurum',
    'enxofre': 'Enxofre',
    'glisofato': 'Glisofato',
    'mancozebe': 'Mancozebe',
    'sulfentrazona': 'Sulfentrazona',
}
